/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StationNumberRouteImport } from './routes/station.$number'
import { Route as ApiPublicHooksBroadcastNotifyRouteImport } from './routes/api/public/hooks/broadcast-notify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationNumberRoute = StationNumberRouteImport.update({
  id: '/station/$number',
  path: '/station/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBroadcastNotifyRoute =
  ApiPublicHooksBroadcastNotifyRouteImport.update({
    id: '/api/public/hooks/broadcast-notify',
    path: '/api/public/hooks/broadcast-notify',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/station/$number': typeof StationNumberRoute
  '/api/public/hooks/broadcast-notify': typeof ApiPublicHooksBroadcastNotifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/station/$number': typeof StationNumberRoute
  '/api/public/hooks/broadcast-notify': typeof ApiPublicHooksBroadcastNotifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/station/$number': typeof StationNumberRoute
  '/api/public/hooks/broadcast-notify': typeof ApiPublicHooksBroadcastNotifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/station/$number' | '/api/public/hooks/broadcast-notify'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/station/$number' | '/api/public/hooks/broadcast-notify'
  id:
    | '__root__'
    | '/'
    | '/station/$number'
    | '/api/public/hooks/broadcast-notify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StationNumberRoute: typeof StationNumberRoute
  ApiPublicHooksBroadcastNotifyRoute: typeof ApiPublicHooksBroadcastNotifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station/$number': {
      id: '/station/$number'
      path: '/station/$number'
      fullPath: '/station/$number'
      preLoaderRoute: typeof StationNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/broadcast-notify': {
      id: '/api/public/hooks/broadcast-notify'
      path: '/api/public/hooks/broadcast-notify'
      fullPath: '/api/public/hooks/broadcast-notify'
      preLoaderRoute: typeof ApiPublicHooksBroadcastNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StationNumberRoute: StationNumberRoute,
  ApiPublicHooksBroadcastNotifyRoute: ApiPublicHooksBroadcastNotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
